### ISSUE TITLE
List attribute function?

### ISSUE THREAD

**Issue by youngjaewoo** [jonathanBieler/BioMart.jl#2]
Thanks for this work. I was wondering if it's possible to access a list of attributes available for a given dataset. For instance, 

```
BioMart.Dataset("hsapiens_gene_ensembl") |> list.attributes

> ["ensembl_gene_id", "go_id", ...]
```

What do you think?

**Comment by jonathanBieler** [comment]
It's probably possible yes, we just need to figure out how to get that info from the biomart web service, I had a quick look but haven't found it, maybe I need to check the R package source code.

Note that this package is a bit experimental, I was thinking about integrating this into Bio.jl ecosystem but there's probably some work to be done. If you have some ideas about the interface of other things don't hesitate to contribute.

**Comment by youngjaewoo** [comment]
Never contributed before, but I can try. Think it's a good addition to Bioservices.jl

Biomart web doesn't explain explicitly. So I will check the R code too. Alternatively, I can help with useful attribute items as part of documentation (looks easier to me).

**Comment by jonathanBieler** [comment]
Found it, we just need to make the query and parse the resulting xml (similar to [this](https://github.com/jonathanBieler/BioMart.jl/blob/master/src/Database.jl#L26)):

```
http://www.ensembl.org/biomart/martservice?type=configuration&dataset=hsapiens_gene_ensembl
```

**Comment by youngjaewoo** [comment]
Cool. I tried parsing here.

```
using HTTP, DataFrames

# read text
r = HTTP.get("http://www.ensembl.org/biomart/martservice?type=configuration&dataset=hsapiens_gene_ensembl", cookies=true) ;
data = String(r.body) ;

### split the whole text by lines
data = split(data, "\n") ; # split by lines

### get feature names (Attribute Names)
# get all lines with "AttributeDescription key="
idx_AD = findall(occursin.("AttributeDescription key=", data))

### for each line get feature.name and short description
featurenames, displaynames = String[], String[]
for (i,line) in enumerate(data[idx_AD])
    if occursin("displayName=", line) & occursin("internalName=", line)
        # get string that contains ` internalName==\"...\" `
        text_f = match(r"internalName=\".*?\"", line).match
        text_f = match(r"\".*?\"", text_f).match
        s_featurename = replace(text_f, "\""=>"")

        # get string that contains ` displayName=\"...\" `
        text_dn = match(r"displayName=\".*?\"", line).match
        text_dn = match(r"\".*?\"", text_dn).match
        s_displayname = replace(text_dn, "\""=>"")

        push!(featurenames,  s_featurename)
        push!(displaynames, s_displayname)
    else
        println(idx_AD[i], "th line does not have both displayName and internalName for parsing")
        println(line, "\n")
    end
end
attribute_dat = DataFrame(AttributeName=featurenames, AttributeDescription=displaynames)
```

This produces some like the below.
<img width="830" alt="image" src="https://user-images.githubusercontent.com/8863211/76091461-99951a80-5f8b-11ea-84b4-ff4f78a4d7cb.png">


What do you think?

**Comment by youngjaewoo** [comment]
I spot-tested the AttributeNames collected above, and they work.

```
querylist = [ "ENSMUSG00000030232", "ENSMUSG00000038518" ]
q = BioMart.Query(
    BioMart.Dataset("mmusculus_gene_ensembl"),
    BioMart.Attributes("external_gene_name", "ensembl_gene_id", "chromosome_name", "start_position", "end_position", "external_gene_name", "ssalar_homolog_dn"),
    BioMart.Filter(ensembl_gene_id = querylist)
)
q()
```
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/8863211/76092559-9569fc80-5f8d-11ea-8d6d-b63e4496ef41.png">


However, one inconvenience is that there are many not-so-useful attributes being collected (e.g. Atlantic salmon gene name). I will extract Attribute Category labels that can be used to give higher level description of AttributeNames.

**Comment by jonathanBieler** [comment]
Cool thanks,  although it probably would be better to use a XML parser (I'm using LightXML.jl in this package), e.g. something like this :

```julia
using LightXML, HTTP

"""go recursively over the XML and collect `AttributeDescription`s"""
function collect_elems(node, out) 

    if name(node) == "AttributeDescription"
        el = XMLElement(node)
        push!(out, 
            (
             internalName = attribute(el, "internalName"),
             displayName  = attribute(el, "displayName"),
            )
        )
    else
        for c in child_nodes(node)
            collect_elems(c, out)
        end
    end
    out
end 
collect_elems(node) = collect_elems(node, [])


r = HTTP.get("http://www.ensembl.org/biomart/martservice?type=configuration&dataset=hsapiens_gene_ensembl", cookies=true)
data = String(r.body)

xdoc = parse_string(data)
xroot = root(xdoc)

out = collect_elems(xroot)
DataFrame(out)
```

I can integrate that into the package if you are happy with the output.

**Comment by youngjaewoo** [comment]
Looks great! I didn't really know how to use XML parsers. Thanks.

One more question. Is there a way to make it so that..

```
BioMart.Dataset("hsapiens_gene_ensembl") |> list.attributes

> DataFrame of Attributes
```

or 

```
get_attributes(BioMart.Dataset("hsapiens_gene_ensembl"))

> DataFrame of Attributes
```

Or what do you think is the best implementation?

**Comment by jonathanBieler** [comment]
I've pushed a commit with these changes, with a method that takes a `Dataset` instead of a `String` :

https://github.com/jonathanBieler/BioMart.jl/blob/master/src/Dataset.jl#L44

It's also memoized (it caches the results), so calling it several times is fast.

**Comment by youngjaewoo** [comment]
Awesome! Thanks for this
