### ISSUE TITLE
Modification required to work in Julia 1.7

### ISSUE THREAD

**Issue by itcosyne** [jonathanBieler/BioMart.jl#3]
Hi, 
With the new versions of Julia, you need to do the following modification in the Query.jl file
(It specifies that the file is read into a DataFrame)

function execute(q::Query) 
    query = HTTP.URIs.escapeuri(string(q.xdoc))
    r = HTTP.get(string(BIOMART_URL, "?query=", query))
    **CSV.read(r.body, DataFrames.DataFrame, delim = '\t')**
end

great package, by the way.
Irene

**Comment by jonathanBieler** [comment]
@itcosyne thanks for the report, it should be fixed now (you have to do `]up` in the package manager). I also cleaned up a few things, I might register this package actually.
